RedditClone/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resource :session, only: [:new, :create, :destroy]
  resources :users, only: [:new, :create]
  resources :subs do
    resources :posts, except: [:index]
  end
end

RedditClone/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

RedditClone/app/models/comment.rb
class Comment < ApplicationRecord
end

RedditClone/app/models/post.rb
class Post < ApplicationRecord
  validates :title, :content, presence: true

  belongs_to :sub

  belongs_to :author,
  primary_key: :id,
  foreign_key: :author_id,
  class_name: :User

end

RedditClone/app/models/post_sub.rb
class PostSub < ApplicationRecord
end

RedditClone/app/models/sub.rb
class Sub < ApplicationRecord

  validates :title, :description, presence: true

  has_many :posts

  belongs_to :moderator,
  primary_key: :id,
  foreign_key: :moderator_id,
  class_name: :User

end

RedditClone/app/models/user.rb
class User < ApplicationRecord
  validates :password_digest, :session_token, :username, presence: true
  validates :password, length: { minimum: 6, allow_nil: true }

  after_initialize :ensure_session_token

  has_many :subs,
  primary_key: :id,
  foreign_key: :moderator_id,
  class_name: :Sub

  has_many :posts,
  primary_key: :id,
  foreign_key: :author_id,
  class_name: :Post

  attr_reader :password

  def password=(pw)
    @password = pw
    self.password_digest = BCrypt::Password.create(pw)
  end

  def is_password?(pw)
    BCrypt::Password.new(self.password_digest).is_password?(pw)
  end

  def ensure_session_token
    self.session_token ||= SecureRandom::urlsafe_base64
  end

  def reset_session_token!
    self.session_token = SecureRandom::urlsafe_base64
    self.save!
    self.session_token
  end

  def self.find_by_credentials(username , pw)
    user = User.find_by(username: username)
    return nil unless username
    user.is_password?(pw) ? user : nil
  end

end

RedditClone/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  helper_method :current_user, :logged_in

  def login(user)
    @current_user = user
    session[:session_token] = user.session_token
  end

  def logout
    current_user.reset_session_token!
    session[:session_token] = nil
  end

  def current_user
    @current_user ||= User.find_by(session_token: session[:session_token])
  end

  def logged_in?
    !!current_user
  end

  def require_logged_in
    redirect_to new_session_url unless logged_in?
  end
end

RedditClone/app/controllers/comments_controller.rb
class CommentsController < ApplicationController
end

RedditClone/app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :require_logged_in, except: [:show]

  def new
    @post = Post.new
    render :new
  end

  def create
    @post = Post.new(post_params)
    @post.author_id = current_user.id
    @post.sub_id = params[:sub_id]
    if @post.save
      redirect_to sub_post_url(@post.sub_id, @post.id)
    else
      flash.now[:errors] = @post.errors.full_messages
      render :new
    end
  end

  def edit
    @post = Post.find_by(id: params[:id])
    render :edit
  end

  def show
    @post = Post.find_by(id: params[:id])
    render :show
  end

  def update
    @post = Post.find_by(id: params[:id])
    if @post && @post.author_id == current_user.id
      if @post.update_attributes(post_params)
        redirect_to sub_post_url(@post.sub_id, @post.id)
      else
        flash.now[:errors] = @post.errors.full_messages
        render :edit
      end
    else
      flash.now[:errors] = ["You are not the author of this post"]
      render :edit
    end
  end

  def destroy
  end

  private

  def post_params
    params.require(:post).permit(:title, :url, :content)
  end
end

RedditClone/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
    @user = User.new
    render :new
  end

  def create
    @user = User.find_by_credentials(params[:user][:username], params[:user][:password])
    if @user
      login(@user)
      redirect_to subs_url
    else
      flash.now[:errors] = ["Invalid username or password"]
      render :new
    end
  end

  def destroy
    logout
    redirect_to new_session_url
  end

  def user_params
    params.require(:user).permit(:username, :password)
  end

end

RedditClone/app/controllers/subs_controller.rb
class SubsController < ApplicationController
  before_action :require_logged_in, except: [:show, :index]
  def create
    @sub = Sub.new(sub_params)
    @sub.moderator_id = current_user.id
    if @sub.save
      redirect_to sub_url(@sub)
    else
      flash.now[:errors] = @sub.errors.full_messages
      render :new
    end
  end

  def update
    @sub = Sub.find_by(id: params[:id])
    if @sub && @sub.moderator == current_user
      if @sub.update_attributes(sub_params)
        redirect_to sub_url(@sub)
      else
        flash.now[:errors] = @sub.errors.full_messages
        render :edit
      end
    else
      flash.now[:errors] = ["You are not the moderator of this sub"]
      render :edit
    end
  end

  def destroy
    @sub = Sub.find_by(id: params[:id])
    if @sub && current_user == @sub.moderator
      @sub.destroy
      redirect_to subs_url
    else
      flash.now[:errors] = ["You can not delete a sub that you don't moderate"]
    end
  end

  def edit
    @sub = Sub.find_by(id: params[:id])
    render :edit
  end

  def index
    @subs = Sub.all
    render :index
  end

  def show
    @sub = Sub.find_by(id: params[:id])
    render :show
  end

  def new
    @sub = Sub.new
    render :new
  end

  private
  def sub_params
    params.require(:sub).permit(:title, :description)
  end
end

RedditClone/app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
    render :new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      login(@user)
      redirect_to subs_url
    else
      flash.now[:errors] = @user.errors.full_messages
      render :new
    end
  end

  private

  def user_params
    params.require(:user).permit(:username, :password)
  end

end

RedditClone/app/helpers/application_helper.rb
module ApplicationHelper
end

RedditClone/app/helpers/comments_helper.rb
module CommentsHelper
end

RedditClone/app/helpers/posts_helper.rb
module PostsHelper
end

RedditClone/app/helpers/sessions_helper.rb
module SessionsHelper
end

RedditClone/app/helpers/subs_helper.rb
module SubsHelper
end

RedditClone/app/helpers/users_helper.rb
module UsersHelper
end

RedditClone/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RedditClone</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>

    <% if current_user %>
    <%= "Hi #{current_user.username}" %>
    <%= button_to "Sign Out", session_url, method: :delete %>
    <% end %>
    <%= yield %>

    <%= flash[:errors] %>
  </body>
</html>

RedditClone/app/views/posts/edit.html.erb
<h1>Edit post</h1>

<form action="<%= sub_post_url(@post.sub_id, @post.id) %>" method="post">
  <input type="hidden" name="_method" value="PATCH">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">

  <label for="Title">Title</label>
  <input id="Title" type="text" name="post[title]" value="<%= @post.title if @post %>">

  <br>
  <label for="URL">URL</label>
  <input id="URL" type="text" name="post[url]" value="<%= @post.url if @post %>">
  <br>

  <label for="Content">Content</label>
  <textarea id="Content" name="post[content]">
    <%= @post.content if @post %>
  </textarea>

  <input type="submit" value="Update Post!">
</form>

<%= link_to "View All Subs", subs_url %>

RedditClone/app/views/posts/new.html.erb
<h1>Make a post</h1>

<form action="<%= sub_posts_url(@post.sub_id) %>" method="post">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">

  <label for="Title">Title</label>
  <input id="Title" type="text" name="post[title]" value="<%= @post.title if @post %>">

  <br>
  <label for="URL">URL</label>
  <input id="URL" type="text" name="post[url]" value="<%= @post.url if @post %>">
  <br>

  <label for="Content">Content</label>
  <textarea id="Content" name="post[content]">
    <%= @post.content if @post %>
  </textarea>

  <input type="submit" value="Create Post!">
</form>

<%= link_to "View All Subs", subs_url %>

RedditClone/app/views/posts/show.html.erb
<%= @post.title %>
<%= @post.content %>
<%= @post.author.username %>
<%= link_to "Edit Post", edit_sub_post_url(@post) %>

<%= link_to "View All Subs", subs_url %>

RedditClone/app/views/subs/edit.html.erb
<h1>Edit Sub</h1>

<form action="<%= sub_url(@sub) %>" method="post">
  <input type="hidden" name="_method" value="PATCH">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">

  <label for="Title">Title</label>
  <input id="Title" type="text" name="sub[title]" value="<%= @sub.title if @sub %>">

  <label for="Description">Description</label>
  <textarea id="Description" name="sub[description]">
    <%= @sub.description if @sub %>
  </textarea>

  <input type="submit" value="Update!">
</form>

<%= link_to "View All Subs", subs_url %>

RedditClone/app/views/subs/index.html.erb
<% @subs.each do |sub_reddit| %>
<%= sub_reddit.title %>
<br>
<%= sub_reddit.description %>
<br>
<%= link_to "View", sub_url(sub_reddit) %>
<%= link_to "Edit", edit_sub_url(sub_reddit) %>
<%= button_to "Delete", sub_url(sub_reddit), method: :delete %>
<br>
<br>
<% end %>

<%= link_to "View All Subs", subs_url %>

RedditClone/app/views/subs/new.html.erb
<h1>Create a sub</h1>

<form action="<%= subs_url %>" method="post">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">

  <label for="Title">Title</label>
  <input id="Title" type="text" name="sub[title]" value="<%= @sub.title if @sub %>">

  <label for="Description">Description</label>
  <textarea id="Description" name="sub[description]">
    <%= @sub.description if @sub %>
  </textarea>

  <input type="submit" value="Create!">
</form>

<%= link_to "View All Subs", subs_url %>

RedditClone/app/views/subs/show.html.erb
<%= @sub.title %>
<br>
<%= @sub.description %>
<br>
<%= @sub.moderator.username %>
<br>
<%= link_to "Edit", edit_sub_url(@sub) %>
<%= button_to "Delete", sub_url(@sub), method: :delete %>
<br>
<br>

<%= link_to "View All Subs", subs_url %>

<h1>All Posts For This Sub</h1>
<% @sub.posts.each do |post| %>
<%= post.title %> <br>
<%= link_to "View Post", sub_post_url(post.sub_id, post.id) %>
<%= link_to "Edit Post", edit_sub_post_url(post.sub_id, post.id) %>
<br>
<br>
<% end %>

<%= link_to "Create New Post", new_sub_post_url(@sub.id) %>

RedditClone/app/views/users/new.html.erb
<h1>Sign Up</h1>

<form action="<%= users_url %>" method="post">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">

  <label for="Username">Username</label>
  <input id="Username" type="text" name="user[username]" value="<%= @user.username if @user %>">

  <label for="Password">Password</label>
  <input id="Password" type="password" name="user[password]">

  <input type="submit" value="Sign Up">

</form>